import '@specialdoom/docure-button';
import '@specialdoom/docure-article-card';
import '@specialdoom/docure-banner';
import '@specialdoom/docure-header';
import '@specialdoom/docure-list';
import '@specialdoom/docure-loading';
import '@specialdoom/docure-result';
import '@specialdoom/docure-article';
import '@specialdoom/docure-recently-viewed';